### ISSUE TITLE
leftrightharpoons and rightleftharpoons not rendering

### ISSUE THREAD

**Issue by sgiacinto** [mathquill/mathquill#1000]
Like the title says, \leftrightharpoons and \rightleftharpoons are not being recognised by the MathQuill input box. 
I've checked Symbola.woff2 (this is the one loading) and it definitely contains these glyphs. 
Every other character I've tried is working, only these 2 are not. 

Mathquill Ver. 0.10.1, 
Jquery 3.6.1, 
using mathquill.js (not mathquill-basic.js) 

Not an expert with Latex so apologies if this is a simple question.

**Comment by drlippman** [comment]
There are a lot of latex symbols that mathquill doesn't have defined, and these are two of them.  You could add support to your version by defining the new symbols in `/src/commands/math/advancedSymbols.js`.  You'd need to add a line like

`LatexCmds.rightleftharpoons = bind(BinaryOperator,'\\rightleftharpoons ',&rlhar;');`

**Comment by sgiacinto** [comment]
Very nice, works like a charm. 
Thanks a lot for the quick and accurate answer.
