### ISSUE TITLE
JQuery update version

### ISSUE THREAD

**Issue by hellnhell** [mathquill/mathquill#1001]
I'm having security issues in my web because of the library using an old version of jQuery (jQuery before 3.0.0 is vulnerable to Cross-site Scripting (XSS) attacks when a cross-domain Ajax request is performed without the dataType option, causing text/javascript responses to be executed). It's recommended to update to 3.5.0 or later. Can anybody do this?

**Comment by jwmerrill** [comment]
Mathquill does not bundle its own copy of jQuery. Users of the library are required to provide their own jQuery. So you should be able to upgrade jQuery independently, without upgrading mathquill.
