### ISSUE TITLE
Cannot start a new line in textbox

### ISSUE THREAD

**Issue by CedricLeong** [mathquill/mathquill#174]
There is no way to start a new line in math-editble content. You have to make a new math editable.

**Comment by anyibuofu** [comment]
@jneen any chance this of this feature?

**Comment by laughinghan** [comment]
@anyibuofu There are currently no plans to add this feature. I think Jeanine was talking about `\vector{}`, which was half-baked and has since been removed.

PRs are welcome, as is sponsorship for this feature.

**Comment by dimitardanailov** [comment]
Hello, 

I am using: 

`\\textcolor{black}{\\text{newline}}`

and combine with: 

```css
.mq-textcolor .mq-text-mode {
    display: block;
}
```

[![https://gyazo.com/d849edff10c3c1c941a218eb2a6063a5](https://i.gyazo.com/d849edff10c3c1c941a218eb2a6063a5.gif)](https://gyazo.com/d849edff10c3c1c941a218eb2a6063a5)

**Comment by gauravbhavsar** [comment]
@dimitardanailov Thanks for solution, its solve my problem.
I am trying to bind new line concept into ENTER key event, when word is not starting with \ (back slash).
but I do not know how to achieve this.

**Comment by rakirme** [comment]
@dimitardanailov  hi can you please explain it further. im new to mathquill and im trying to understand it  but i cant. Maybe there's something that i missed or dont know of yet

**Comment by Pankaj1008** [comment]
backspace not working in \\textcolor{black}{\\text{newline}} , it require three to four time backspace to goto previous line, it throws [Uncaught TypeError: Cannot read property 'nodeType' of null ] error
