### ISSUE TITLE
Mathquill converts space char into "\:" but not vice versa

### ISSUE THREAD

**Issue by asavoy** [mathquill/mathquill#19]
It's a rather minor bug, but I thought it would be good to note down.
### Test
- http://laughinghan.github.com/mathquill/demo.html
- Enter <code>y=a b</code> (that is, y "equals" a "space" b) into the field "Mathquill editable math"
- Observe that the latex source is <code>y=a:b</code>
- Modify latex source to <code>y=a:b:c</code>
- Observe that the field "Mathquill editable math" now prints <code>y=a:b:c</code>, whereas it is expected to display <code>y=a b c</code>

**Comment by Visagalis** [comment]
short explaination to this bug:
```javascript
$('#input').mathquill('latex','a\\text{ }b');
```
this shows this text: "a b"
```javascript
$('#input').mathquill('latex','a\\:b');
```
this shows this text: "" <- its completely empty.

**Comment by ericjs496** [comment]
try \test{:}  
may be able to solve your problem~
