### ISSUE TITLE
Undefined jQ[0] in PlusMinus respace method

### ISSUE THREAD

**Issue by eoghanmcilwaine** [mathquill/mathquill#273]
It's a bit convoluted - if you try to use an \editable{} inside an exponent, followed by a PlusMinus symbol, the jQ object isn't available and rendering fails.

Here's an example with the latex `x^\editable{}+1`
http://eoghanmcilwaine.github.io/mathquill/exponent-editable.html

The error is
`Uncaught TypeError: Cannot set property 'className' of undefined mathquill.js:2772`

I'm getting around it by doing a `if (this.jQ.length)` check inside the respace function, but thought I should log it in case it indicates anything more serious.

**Comment by jwmerrill** [comment]
Appears to be fixed on master
