### ISSUE TITLE
spaceBehavesLikeTab and leftRightIntoCmdGoes should be global options

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#291]
Is there some rationale for the way that options are split between per-instance and global?

`disableCharsWithoutOperand`, `addCharsThatBreakOutOfSupSub`, and `addAutoCommands` are global, but `spaceBehavesLikeTab` and `leftRightIntoCmdGoes` are per-instance.

**Comment by laughinghan** [comment]
Fixed by #336.
