### ISSUE TITLE
[dev] Both native and MathQuill cursors are visible on iOS

### ISSUE THREAD

**Issue by alopatin** [mathquill/mathquill#310]
As of the latest commit (1e6aa06e6c) both the native and MathQuill cursors are visible when you focus into a MathQuill input on iOS, which is visually confusing:

![mq](https://cloud.githubusercontent.com/assets/238458/2978355/830c0290-dbb8-11e3-8f72-67a0a98c964b.gif)

The above gif is Chrome on iOS 7, but Safari shows the same behavior as well. Haven't tested any Android browsers.

This is a blocker for deploying a MathQuill integration to mobile web users.

**Comment by jsg2021** [comment]
its visible in iOS9.
