### ISSUE TITLE
Mathquill Editable field desn't  functionnal in android chrome browsers

### ISSUE THREAD

**Issue by chenning84** [mathquill/mathquill#331]
I am using latest version 0.9.3 of Mathquil  which I download from http://mathquill.com/downloads.html

The issue is similar to  https://github.com/mathquill/mathquill/issues/65
Browser: Chrome
Cannot type anything which is problematic.

I try to add following debug code to demo page 

$( "#editable-math" ).on( "keydown", function( event ) {
console.log( event.which======="+event.which);
});
$( "#editable-math" ).on( "keyup", function( event ) {
console.log(" event.which==="+event.which);
});

both events were triggered but  event.which returns 0 for any key press . 

I tried to follow the thread of #65 but noticed the code base is different .

**Comment by kyvaith** [comment]
While this issue won't be fixed in webkit/blink is there any plan to solve this on MathQuill site? It's urgent for us.
