### ISSUE TITLE
License explanation is confusing me

### ISSUE THREAD

**Issue by hyandell** [mathquill/mathquill#341]
Hi,

The bottom of the readme explains the MPL 2.0 by saying "The quick-and-dirty is you can do whatever as long as modifications to MathQuill itself are in public GitHub forks."

That seems to clash with MPL 2.0's FAQ (https://www.mozilla.org/MPL/2.0/FAQ); specifically Q6 which says you can modify privately without having to make a public release, and Q9 and Q10 which don't require modifications be made as GitHub forks.

Could I suggest clarifying this by saying:

 "The quick-and-dirty is you can do whatever as long as distributed modifications to MathQuill itself are made public, for example in GitHub forks."

Thanks.

**Comment by laughinghan** [comment]
Yeah, I said "if" not "iff", what could possibly be confusing about that?

I'll try to clarify by adding a link to the MPL 2.0 FAQ. I don't want to complicate the "quick-and-dirty" explanation, that's targeted at the most common case of people playing around in public forks.
