### ISSUE TITLE
Unable to render some latex expression in to html using mathquill

### ISSUE THREAD

**Issue by mandavavinay** [mathquill/mathquill#381]
Hi,
Here is what i am binding in to text box('#taThree') in jquery using mathquill. But it is appending  left  and ight int the html. am I doing any thing wrong.
$('#taThree').mathquill('latex', '\left(x^2 + y^2 \right)');

**Comment by jwmerrill** [comment]
You need to escape slashes in javascript strings, so you want

`$('#taThree').mathquill('latex', '\\left(x^2 + y^2 \\right)');`

**Comment by mandavavinay** [comment]
Thanks alot

On Fri, Mar 6, 2015 at 12:52 AM, Jason Merrill <notifications@github.com>
wrote:

> You need to escape slashes in javascript strings, so you want
>
> $('#taThree').mathquill('latex', '\\left(x^2 + y^2 \\right)');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mathquill/mathquill/issues/381#issuecomment-77432328>.
>



-- 
Vinay Mandava
91-9885127836
