### ISSUE TITLE
In autoSubscriptNumerals mode, don't autosubscript unitalicized commands

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#390]
The rationale here is that typing `sin90` is way more likely to mean `sin 90` than `sin_{90}`.

**Comment by eluberoff** [comment]
+1 on this, I think we need this pre-desmos-update-launch.
we get a fair bit of `log 100`, `sin 30`, etc.

**Comment by jwmerrill** [comment]
Fixed by #398.
