### ISSUE TITLE
Parens are fuzzy when auto-expanding

### ISSUE THREAD

**Issue by eluberoff** [mathquill/mathquill#394]
To repro,
(1) type "("
(2) type "1/2/3/4"

Observed: fuzzy parentheses. Expected: crisp parentheses.

For comparison: in the top one, the paren was added and then populated. In the bottom one, the fraction was created and then the parens were applied:

![screen shot 2015-05-15 at 3 26 45 pm](https://cloud.githubusercontent.com/assets/478331/7662860/d0ff7562-fb16-11e4-83cf-e877112df5c7.png)

**Comment by jwmerrill** [comment]
Neither of these looks really great. It looks like the top screenshot is using antialiasing and the bottom screenshot isn't, but neither one has the parens rendered as nicely as the numerals.

**Comment by laughinghan** [comment]
This doesn't happen in Firefox or even Safari on my MBP, only Chrome. Also, goes away and comes back depending on what you type in front of the parentheses. This shit is bananas.

I'm tempted to just ignore this and it'll go away when we eventually steal KaTeX's/MathJax's paren-rendering strategy (they have huge sizes of parens in their font).

**Comment by eluberoff** [comment]
good call. observing the same (both that it's just chrome and that it's totally bananas).
#iceboxit!
