### ISSUE TITLE
option: deleting one parenthesis deletes both

### ISSUE THREAD

**Issue by eluberoff** [mathquill/mathquill#396]
I absolutely love ghost parens, but the behavior when deleting doesn't feel quite right. Specific case that keeps throwing me off:

(1) type `sin(x)`
(2) delete that first paren after `sin`

Expected: parens cleared.
Observed: (sin x) (with the first paren as a ghost paren)

This definitely feels wrong to me. I think clearing out parens would feel better to me. It's possible that this is only true when deleting from inside the parens -- so backspacing the opening paren clears parens, or deleting the closing paren. For simplicity, I'd prefer either an option (or default) that deleting either hardened paren deletes the other one also.

**Comment by laughinghan** [comment]
Didn't @jwmerrill deal with this in Desmos by having the `sin()` button actually just type `sin(`?

The thing about this is that it's path-dependent, right? If you have `a+b` and you're trying to wrap the `b` in parens and you write the close-paren first, so with the ghost it's `(a+b)`, and then you try to type an open-paren but mistakenly type it before the plus sign so you have `a(+b)`, and you backspace over the open-paren, you don't want to clear the close-paren, you want it to stay there so you can move over and write the open paren and get `a+(b)`, right?

Also, for what it's worth, maybe you've just gotten used to MathQuill's weird behavior? In normal text, you expect to have to backspace over both parens, right?

**Comment by eluberoff** [comment]
I think the case you describe is pretty edge case. Basically, I think that folks (well, I) more often delete a paren because I want to get rid of them than because I want to move one, especially since ghost parens are so freaking awesome/intuitive for entering parens initially.

So, deleting both (current master-branch mathquill behavior) results in (excluding moving the cursor):
2 strokes -> 3 strokes for moving a parenthesis (remove them, add 2 new ones with sweet ghost parens)
2 strokes -> 1 stroke for removing parentheses

IMO, worth the trade-off. If there's disagreement on that, a flag seems reasonable. I'm pretty sure it's what Desmos will want to use.

**Comment by eluberoff** [comment]
oh and jwmerrill's fix is a good one, but there are a ton of other ways for you to end up with parens that you'd like to clear. another one: lots of people type parens to form fractions because they don't know about selecting and then dividing. So you end up with (1+2)/3 and then want to clear off the parens. They harden immediately on dividing, so peeling the parens is more of an ordeal if you need to delete both sides independently.

**Comment by jwmerrill** [comment]
Let's try to come to a consensus on the best behavior here before we start talking about making an option.

I think a good test for whether something should be an option is whether there is some category of _users_ that will be better served by one option, and a different category that will be better served by the others. Usually, that distinction is going to be between "beginners," and "people already familiar with LaTeX," but there might be other valid categories. I can't think of anything like that for what happens when you delete one paren in a pair.

Every option we add makes it more difficult to get started with Mathquill, and to feel confident that you've configured it appropriately. We shouldn't use them as an escape hatch to avoid having to come to a consensus.

**Comment by jwmerrill** [comment]
FWIW, I'd rather have either of these than have an option, but if I had to cast a vote right now, I'd vote for the behavior suggested by Eli. I think deleting parens around a numerator is a fairly compelling example, and I also think the behavior you get when you start deleting from `sin(x|)` with a little jarring, granting that we've made that a less likely scenario by creating ghost parens from functions in our keypad.

**Comment by eluberoff** [comment]
Played with this a bunch, and realized that I missed the mark a bit with this ticket. What feels best to me is to peel off the right-side paren whenever we delete the left side paren.

Boiled down to a general principle: it feels strange when a keystroke affects things to the /left/ of the cursor.

My prefered fix: #400
