### ISSUE TITLE
[dev] Setting charsThatBreakOutOfSupSub = '+-' makes it hard to type 10^{-6}

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#405]
You end up with `10^{}-6`.

I think we might need to special case +/- being used as unary operators, and not break out of exponents in that case.

**Comment by jwmerrill** [comment]
Re: special casing--maybe we can get away with not doing any special casing, and just say that nothing breaks out of exponents when it's used as the first character. This is the rule currently being used in production Desmos, and it seems to work out fine.

It results in `10^--6` rendering as `10^{-}-6`, which isn't ideal, but I'm not sure that's a case we need to optimize for.

**Comment by laughinghan** [comment]
Sounds good for now.
