### ISSUE TITLE
How can I focus() a mathquill-textbox?

### ISSUE THREAD

**Issue by lentzi90** [mathquill/mathquill#414]
Hello!

I'm trying to focus a mathquill-textbox used in a chat client without success.
I have tried the following:
```
$("#message").mathquill('editable').focus();
$("#message").mathquill().focus();
$("#message").mathquill('latex', '').focus();
```
Any suggestions?

In case you are interested in the chat:
I have made a basic chat client + server for the mathstudents at my university. The code can be found [here](https://github.com/lentzi90/math-chat) and a (static) demo [here](http://lentzi90.github.io/math-chat/). I want to focus the message field after the nickname is entered.

**Comment by edborden** [comment]
I had to do something similar and ended up getting it to work like this:
`$("#message").mathquill('latex', '').mousedown().mouseup();`

**Comment by lentzi90** [comment]
Thanks, it worked perfectly! :+1:
