### ISSUE TITLE
How to show the text with spaces between them in Mathquill

### ISSUE THREAD

**Issue by mandavavinay** [mathquill/mathquill#433]
I have text like this "The\ answer\ for \int x^3 \ is" and when I try to convert this by using mathquill, its not showing any thing. But when i try in http://www.codecogs.com/latex/eqneditor.php its working fine. What could be the reason.

**Comment by laughinghan** [comment]
Is this v0.9.4? I think only the `dev` branch supports spaces `\ `

**Comment by mandavavinay** [comment]
Yeah I am  using v0.9.4. I don't see dev branch wiht mathquill.js on the github. where can i find the dev branch with mathquill.js

**Comment by wolfv** [comment]
https://github.com/mathquill/mathquill/tree/dev

**Comment by mandavavinay** [comment]
I looked at the https://github.com/mathquill/mathquill/tree/dev  branch code, but I don't find any mathquill.js. Did the code got changed. Usually I use only mathquill.js file. Please let me know where can i find the mathquill.js file. Or if it is any other file please let me know.

**Comment by mandavavinay** [comment]
I looked at the https://github.com/mathquill/mathquill/tree/dev branch code, but I don't find any mathquill.js. Did the code got changed. Usually I use only mathquill.js file. Please let me know where can i find the mathquill.js file. Or if it is any other file please let me know.

**Comment by laughinghan** [comment]
On the `dev` branch you have to run `make` to produce `build/mathquill.js`.

Another option is that v0.9.4 supports `\:`.

Sorry this stuff is so sloppy for now

**Comment by raerae13** [comment]
Are there instructions for someone who is not at all familiar with node.js or dealing with make files? I read the Building doc and I've installed node.js, but I'm lost after that.
