### ISSUE TITLE
[dev] Getting "Cannot read property 'prototype' of undefined" after clean build

### ISSUE THREAD

**Issue by Darkneon** [mathquill/mathquill#435]
```make``` ran without any errors. Running the server and going to unit.html page I get this error. 

Error is at line: ```_.selectTowards = MathCommand.prototype.selectTowards;```

Anyone else getting this?

**Comment by Darkneon** [comment]
Found it, issue for me was in the Makefile. It's loading text.js before math.js for some reason. 

I forced it by changing 
```
$(SRC_DIR)/commands/*.js \
``` 
to
```
$(SRC_DIR)/commands/math.js \
$(SRC_DIR)/commands/text.js \
```

Should I make a PR for it?

**Comment by laughinghan** [comment]
Rats, are you on Linux? Maybe on Macs it's always in alphabetical order, so something order-dependent crept in

**Comment by Darkneon** [comment]
Yes, on Linux.

**Comment by lideen** [comment]
+1, on Linux as well

**Comment by d4l3k** [comment]
+1, it's causing issues for me on Linux.

**Comment by laughinghan** [comment]
Another instance: https://mathquill.slack.com/archives/mathquill/p1457634601000193
