### ISSUE TITLE
Wrong symbol for ddots

### ISSUE THREAD

**Issue by deannah** [mathquill/mathquill#438]
In [`symbols.js`](https://github.com/mathquill/mathquill/blob/ecb5c3cb5384e92c72514840afe5ed99fea6b082/src/symbols.js#L434) the latex command `\ddots` is associated with the wrong symbol. It is set as `'&#8944'` which is the symbol for an up right diagonal ellipsis, whereas `\ddots` should be the down right diagonal ellipsis` '&#8945'`. You could also add support for `\iddots` which is the inverse of ddots and is the symbol you currently have, but that isn't standard latex.

**Comment by laughinghan** [comment]
Whoops good catch

**Comment by robinwassen** [comment]
@laughinghan You can close this issue now since it has been resolved.
