### ISSUE TITLE
\R render issue

### ISSUE THREAD

**Issue by scaljeri** [mathquill/mathquill#443]
I have some issues with the symbol `ℝ` (hollow R). Now, when I inject this symbol in the editor I use

    \R

which works. However, when I request the LaTeX from the editor it returns

    \mathbb{R}

Which is ok, except, that when I try to put this into the editor it doesn't work anymore. So it seems that MathQuill doesn't recognise `\mathbb`. The problem is that when I want te edit a formula created by MathQuill it doesn't work. Are there any plans to support `\mathbb` ?

**Comment by laughinghan** [comment]
Eventually, but the intermediate plan is to remove `\R` and the other commands that output `\mathbb`, unless someone wants to volunteer to add proper support for them.

**Comment by scaljeri** [comment]
Ah, ok. Well today we decided to use just `R` :)

**Comment by laughinghan** [comment]
Fixed by #910 anyway :)
