### ISSUE TITLE
[dev] noConflict does not reset window.MathQuill to preInterVerMathQuill

### ISSUE THREAD

**Issue by EvilOatmeal** [mathquill/mathquill#466]
This code won't work, because `interfaceVersion` is not available after `noConflict`:

```js
MathQuill.interfaceVersion(1).noConflict();
MathQuill.interfaceVersion(1).noConflict();
```

**Comment by laughinghan** [comment]
`noConflict()` is like in jQuery

```html
<script>
jQuery = 'whatever';
MathQuill = 'whatever2';
</script>
<script src="jquery.js"></script>
<script src="mathquill.js"></script>
<script>
console.log(jQuery); // function $() { ... }
console.log(MathQuill); // function MathQuill() { ... }

jQuery.noConflict();
console.log(jQuery); // whatever

MathQuill.interfaceVersion(1).noConflict();
console.log(MathQuill); // whatever2
</script>

**Comment by EvilOatmeal** [comment]
Ok. But this isn't about MQ being overridden by something else, it's about it overriding itself because you are required to use `interfaceVersioning`.

This means that if you have two third-party script that uses the same InterVer of MQ you have to include MQ twice, because there is no way for them both to initialize themselves.

```html
<script src="mathquill.js"></script>
<script>MathQuill.interfaceVersion(1);</script>
<script src="mathquill.js"></script>
<script>MathQuill.interfaceVersion(1);</script>
```

Sorry about creating two issue about the same thing, sort of, but I feel that this issue represents the short-term fix for this issue and that #464 has turned into the long-term discussion.

This is the code that triggered this whole concern of mine, when I updated to the latest dev commit that uses InterVer (this is an Angular directive that is used in multiple applications of ours, so we can consider it third-party to those applications.)

```js
// NOTE: If we use MathQuill somewhere else we have to move the "interface version" declaration to some central place.
// https://github.com/mathquill/mathquill/issues/464
var mathQuill = $window.MathQuill.interfaceVersion(1);

function link($scope, $element) {
	var mathField = mathQuill.MathField($element[0]).latex($scope.latex);
```

**Comment by laughinghan** [comment]
There's no short-term fix, I need your help getting this right before I can release. InterVer _is_ MathQuill's backcompat story, it needs to be good.

**Comment by EvilOatmeal** [comment]
Well then I'm closing this issue so we can keep the discussion in #464 instead.
