### ISSUE TITLE
Rendering \mathbb fails

### ISSUE THREAD

**Issue by pesasa** [mathquill/mathquill#47]
Rendering \mathbb{R} (and N, Z, C, Q, ...) fails.

Steps to reproduce:
1) Go to demo page: http://laughinghan.github.com/mathquill/demo.html
2) In mathquill-box enter: \R<space>
3) This is rendered as ℝ and latex source shows: "\mathbb{R}
4) In Latex source -box add a space in the end. Mathquill-box shows now: "mathbb{R" in text-mode.
5) In Mathquill-box move cursor. Latex source shows: "\text{mathbb}{R"

Additionally, anything after \R is not shown at all.

**Comment by laughinghan** [comment]
Fixed by #910
