### ISSUE TITLE
on backspace it removes \sin char by char

### ISSUE THREAD

**Issue by scaljeri** [mathquill/mathquill#492]
Maybe not a very clear title, but let me explain. If I type in Mathquill

    \sin 

When I hit backspace I get `si` than `s` and then its removed. Same with 

   \le

When I hit backspace I get `<` and if I hit backspace again it is removed. 

Any ideas why this is happening, because I expect the whole thing to be removed at once ?

**Comment by mjdesa** [comment]
@scaljeri I believe that this functionality is expected. The symbol `\le` has a one character representation, `<`. While the symbol `\sin` has a three character representation, `s` `i` `n`. Intuitively I think this makes sense, would you disagree?

Additionally, in Mathquill, the `\sin` symbol can be expressed by simply typing the characters `s` `i` `n`.

**Comment by mjdesa** [comment]
Closing in favor of https://github.com/mathquill/mathquill/issues/490

**Comment by scaljeri** [comment]
Sorry, I see I forgot to mention one more thing :) If I type `\sin` and then `space`. Then when I hit backspace the characters are deleted one-by-one. 
Furhter more, `\le` is less than or equal (≤) And the weird thing is that when I type `\le` + `space` and then backspace I get <

**Comment by kschaefe** [comment]
I would think that `autoOperatorNames` that converts `sin` to the operator would delete by character, but `\sin` is a single piece of LaTeX and I would expect that to be deleted as a single operation.  The difference being the explicit usage of the `\` character to represent intent of the user.

**Comment by mjdesa** [comment]
@scaljeri ah! As a side note typing the characters `<` `=` will also generate the `\le`. Could you make a note on  https://github.com/mathquill/mathquill/issues/490 with your use case?

@kschaefe So are you suggesting that deleteing any operator in `autoOperatorNames` will delete the entire `\sin`?

**Comment by kschaefe** [comment]
No, I think the reverse actually.  autoOperatorNames signifies things that should convert automatically, so if you enter the non-automatic version, I would treat that as a singleton.

**Comment by mjdesa** [comment]
So you're suggesting that if `sin` is in `autoOperatorNames` and I type `\sin` explicitly, then `delete` will remove the entire operator and if I type `s` `i` `n` and then `delete` I'll get `si`?

**Comment by laughinghan** [comment]
I think that's exactly what @kschaefe is suggesting, but I don't see why anyone would want that. They both export as `\sin`, right? If I do `mathField.latex(mathField.latex())`, which behavior results?

**Comment by kschaefe** [comment]
I thought it made sense for the use case in #490, but after more emails there maybe not.  He's not allowing use entered `sin`.

**Comment by scaljeri** [comment]
I just checked the demo on the mathquill site, and there it seems to work as expected. The whole `\sin` gets removed and you don't get `si` So why doesn't this work on the `dev` branch ?

**Comment by mjdesa** [comment]
@scaljeri the mathquill demo site is a bit outdated. What you're experiencing was a feature that was added a while back. If you note the discussion in https://github.com/mathquill/mathquill/issues/490 we're considering adding an option for the functionality you're looking for.

**Comment by scaljeri** [comment]
ok, I understand! Thnx

**Comment by Pankaj1008** [comment]
enter button on keyboard work with 
handlers: {
                  enter: function() { 
                   $scope.answerMathField.write('\\textcolor{}{\\text{ }}');
               }
            }
but backspace button not working properly, need to press three, four time to back to previous line
