### ISSUE TITLE
Minus and Negative should get different amounts of trailing space

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#523]
![image](https://cloud.githubusercontent.com/assets/48409/13259577/fedb6d4e-da25-11e5-9372-edf267d05a58.png)

![image](https://cloud.githubusercontent.com/assets/48409/13259602/15fce8e0-da26-11e5-8460-3596374fb597.png)

**Comment by laughinghan** [comment]
Oh, thanks! They actually do, the bug you noticed is that following a comma is not one of the cases that's detected as unary negation

![image](https://cloud.githubusercontent.com/assets/225809/13260340/e00fd8c0-da0f-11e5-8351-15ef54b335c5.png)

**Comment by arnog** [comment]
Here are the before and after screenshots...
![screenshot 2016-04-08 15 04 21](https://cloud.githubusercontent.com/assets/760798/14398852/46f4c5aa-fd9c-11e5-8634-ce66790cdf93.png)
![screenshot 2016-04-08 15 01 52](https://cloud.githubusercontent.com/assets/760798/14398851/46f30fa8-fd9c-11e5-83bd-0f4788709878.png)
