### ISSUE TITLE
Keyboard Input not working with Chrome Canary v51.0.2669.0

### ISSUE THREAD

**Issue by ajhyndman** [mathquill/mathquill#540]
I realize Chrome Canary is not a stable browser, nor always worth supporting.  On the other hand, being able to type into Mathquill fields is pretty central to the experience, so I thought I would flag it.

Keyboard input events of any sort do not seem to be triggering any effect in today's (7 Mar, 2016) Chrome Canary build (51.0.2669.0).  This happens in Windows 10 and OS X Yosemite.

**Comment by laughinghan** [comment]
Oh my god thanks! We don't routinely test MathQuill on prerelease channels,
though we really ought to.

Han

**Comment by ajhyndman** [comment]
Awesome!  This looks like a really elegant solution.

**Comment by aameer2** [comment]
is it possible that i get the same issue on Canary (have to type in enter before anything shows up) today?
