### ISSUE TITLE
Inconsistent rendering within ranges

### ISSUE THREAD

**Issue by karoltarasiuk** [mathquill/mathquill#541]
LaTex: `\left(-4,0\right)\left(0,-4\right)`
Screenshot: ![screen shot 2016-03-07 at 4 54 46 pm](https://cloud.githubusercontent.com/assets/1845230/13561818/7c6809e8-e485-11e5-8864-f2a143518789.png)

As you can see the 'minus' in second range has padding and this class applied to its `span`: `mq-binary-operator`.

**Comment by laughinghan** [comment]
Thanks, nice screenshot! This has already been reported and is being tracked at #523
