### ISSUE TITLE
Pressing Enter doesn't trigger 'enter' handler

### ISSUE THREAD

**Issue by laughinghan** [mathquill/mathquill#566]
To repro:
1. on `demo.html`, go to the Console and do `MQ($('#editable-math')[0]).config({handlers: {enter: function() { console.log('enter'); }}})`
2. go into the math field and hit Enter

Expected: `enter` is logged
Observed: nope

**Comment by Greene48** [comment]
any work around for this?

**Comment by The-Penultimate-Defenestrator** [comment]
This might be because `'\n'` isn't actually put in when Enter is pressed. (possibly because of the `preventDefault` call for enter? Maybe that only applies to registering backslash codes.)

I bet there's a better way to handle the `this.register("enter")` than checking for a `\n` character, I would just use the event code. I'll try to see if I can fix this tomorrow if I have time.

**Comment by laughinghan** [comment]
Oh shit that's a good theory, that'd mean it's been broken for...an embarrassingly long time

**Comment by The-Penultimate-Defenestrator** [comment]
@Greene48 This is fixed now. Try again.

**Comment by laughinghan** [comment]
Good news is this will be fixed today; bad news is @The-Penultimate-Defenestrator's fix introduces regressions and will have to be reverted (in Firefox and IE, `Enter` will type whitespace, and not the `&nbsp;` kind either, but the kind that behaves funky if you have multiple in a row and move the cursor left and right through them, thanks to HTML whitespace collapsing).

This is because our theory was wrong: `e.preventDefault()` is never called in the course of pressing `Enter`. This bug is actually because of a pretty wacky browser bug (reported to [Webkit](https://bugs.webkit.org/show_bug.cgi?id=155615#c0) and [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=595943)) due to the `font-size: 0` we set on our textareas to hide the blinking blue cursor on iOS (#452), and is also causing a much more serious problem where typing doesn't work _at all_ in Chrome Canary (#540).

I've broken out fixing that bug into its own ticket: #584

**Comment by Pankaj1008** [comment]
enter button on keyboard work with 
handlers: {
                  enter: function() { 
                   $scope.answerMathField.write('\\textcolor{}{\\text{ }}');
               }
            }
but backspace button not working properly, need to press three, four time to back to previous line
