### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [mathquill/mathquill#569]
I've installed `node` on my server (I usually use Python Flask for backend and vanilla JS for front-end), and managed to run `npm install` without errors. 

Running `make` throws the following error:
```
make
mkdir -p ./build
touch ./build/.exists--used_by_Makefile
rm -rf build/font
cp -r src/font build/font
./node_modules/.bin/lessc  ./src/css/main.less > build/mathquill.css
make: *** [build/mathquill.css] Error 1
```
Any way to fix this?

**Comment by laughinghan** [comment]
> I'd honestly prefer to have a distribution of mathquill that I could download, unzip, and be ready to go.

There is, at the bottom of https://github.com/mathquill/mathquill/releases :

![pasted image at 2016_03_10 02_25 pm](https://cloud.githubusercontent.com/assets/225809/13730535/3ad804fe-e90f-11e5-9b47-b06cf55c2ab6.png)

> ```
> make: *** [build/mathquill.css] Error 1
> ```
That's due to one of the shell commands that `make` is running exiting with a nonzero exit code, can you try running the individual commands and seeing what the actual error message is?

**Comment by The-Penultimate-Defenestrator** [comment]
If I run that command about `less` manually, I get no error. I found the zipped distributions, thanks.

**Comment by laughinghan** [comment]
but `make` still consistently errors?

**Comment by The-Penultimate-Defenestrator** [comment]
Well, after I run that command, it throws an error on this one:
```
cat src/intro.js node_modules/pjs/src/p.js src/tree.js src/cursor.js src/controller.js src/publicapi.js src/services/parser.util.js src/services/saneKeyboardEvent
s.util.js src/services/exportText.js src/services/focusBlur.js src/services/keystroke.js src/services/latex.js src/services/mouse.js src/services/scrollHoriz.js s
rc/services/textarea.js src/commands/math.js src/commands/text.js src/commands/math/advancedSymbols.js src/commands/math/basicSymbols.js src/commands/math/command
s.js src/commands/math/LatexCommandInput.js src/outro.js build/.exists--used_by_Makefile | ./script/escape-non-ascii > build/mathquill.js
make: *** [build/mathquill.js] Error 1
```

**Comment by The-Penultimate-Defenestrator** [comment]
Downloading the zip worked fine, though, I'm not really concerned, so I'll close this.

**Comment by The-Penultimate-Defenestrator** [comment]
The problem that I had was that on my server, `node` pointed to `ax25-node`. The node I wanted was named `nodejs`. I fixed this with `sudo apt-get install nodejs-legacy`.

**Comment by LennyLip** [comment]
I have a problem with current Makefile:

```
/usr/src/mathquill# ./node_modules/.bin/lessc  src/css/main.less > build/mathquill.css
undefinedError: Cannot read property 'eval' of null

/usr/src/mathquill# node --version
v9.4.0

/usr/src/mathquill# ./node_modules/.bin/lessc --version
lessc 3.0.1 (Less Compiler) [JavaScript]
```

Debian 3.16.51-2 

Any suggestions?

**Comment by Giampa** [comment]
Same here with node version 8.9.4. @LennyLip did you solve that?

**Comment by LennyLip** [comment]
@Giampa I just did comment css compilation in the makefile and get css from the release distro

**Comment by Giampa** [comment]
I just noticed that in bin folder there's no less**c** but only less command.
Issuing:

`./node_modules/.bin/less  src/css/main.less > build/mathquill.css`

seems to generate the css without errors...

**Comment by LennyLip** [comment]
Compare your mathquill.css and from distro.

ps. I did have lessc...
