### ISSUE TITLE
\text weirdness

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [mathquill/mathquill#575]
If I put in `\text`, I get a text prompt with no formatting, as expected. However:

1. There's no obvious way to end a text block
2. You can't delete it once you start it. To reproduce:
    - Type `\text` followed by a space. 
    - Press ⌫ (backspace) more than once
    - `TypeError: undefined is not an object (evaluating 'this.text.length')` is thrown.
3. Further weirdness
    - If you follow the steps to reproduce point 2, and then click anywhere outside the box, `mathquill` throws `TypeError: null is not an object (evaluating 'textPcDom.data')`
    - If you follow the steps to reproduce point 2, but press ← (left arrow) after pressing ⌫ only once, a different error is thrown: `TypeError: undefined is not an object (evaluating 'text.charAt')`.

This bug doesn't actually prevent me from doing anything I want to do, just figured I should report it.

**Comment by Greene48** [comment]
I noticed this too. The only way to delete the text block seems to be to ctrl-a select all and then backspace.

Also, somewhat related to this; trying to add a formatted text block using `\textbf` or `\textit` doesn't seem to work. It is just returned as a regular `text{}` block without formatting.

**Comment by The-Penultimate-Defenestrator** [comment]
This seems to be fixed now.

**Comment by laughinghan** [comment]
Yes I think this was fixed Mar 25th by #517.

**Comment by The-Penultimate-Defenestrator** [comment]
Ok. Cool.
