### ISSUE TITLE
this.__controller.blurred

### ISSUE THREAD

**Issue by ajhyndman** [mathquill/mathquill#590]
There are a few checks in the code for the condition:

`if (this.__controller.blurred) {}`

Can anyone explain to me what the intended function is here?  I might not be reading it correctly, but it doesn't look like this can ever possibly evaluate to true.

**Comment by laughinghan** [comment]
It's set to `true` in `focusBlur.js` when the math field is blurred. It's supposed to represent the focus/blur state of the math field.

**Comment by ajhyndman** [comment]
Thanks for the quick response!
