### ISSUE TITLE
Not possible to focus in MathQuill 0.10.0?

### ISSUE THREAD

**Issue by YakovL** [mathquill/mathquill#595]
Hi guys, I'm new here but I've tried to find the answer in docs and also asked in stackoverflow [1], but have got any answers, so probably it's time to ask here. I'm using MathQuill 0.10.0 and second interface

    var MQ = MathQuill.getInterface(2);

creating an editor in this fashion:

    var mathQuillEditor = MQ.MathField(mathQuillField, {
    	spaceBehavesLikeTab: true,
    	handlers: {
    		edit: function() {
    			latexEditor.value = mathQuillEditor.latex(); // update LaTeX field
    			jQuery(latexEditor).change(); // fire updating of CodeCogs
    		}
    	}
    });

What I'm trying to do is to get "focus" inside the editor so that I can type inside `mathQuillEditor` without clicking there with mouse. I haven't found any suggestions how to do this in docs, nor I have succeeded with my own experiments which included:

    mathQuillEditor.moveToRightEnd();
    mathQuillEditor.el().focus();
    jQuery(mathQuillEditor.el()).click()

and also I've tried to `.focus()` and `.click()` each of `$("#containerElement")`, `$("#containerElement .mathquill-editable")`, `$("#containerElement .mathquill-editable .mq-textarea")` and `$("#containerElement .mathquill-editable .mq-empty")` but none of these worked (I guess, some of these are redundant as `mathQuillEditor.el()` returns that `.mathquill-editable` element). I wonder if any of these should work (is it a bug?) or I have to use smth else, so this is either bug report or just question.

[1] http://stackoverflow.com/questions/35976625/how-to-put-cursor-to-the-mathquill-0-10-field-so-that-one-can-type-to-edit-rig

**Comment by laughinghan** [comment]
mathQuillEditor.el() returns the containing span, not the hidden textarea,
focusing it does nothing. Have you tried mathQuillEditor.focus()?

Han

**Comment by laughinghan** [comment]
Oh gosh, that's not documented. Whoops

Han

**Comment by YakovL** [comment]
Great, this works and now is in docs. I think this is to be closed.

**Comment by laughinghan** [comment]
Were you coming from v0.9.x? Should we also add something to the Migration Guide?

**Comment by YakovL** [comment]
No, I'm a newcomer, I'm developing a plugin for Etherpad (actually it's sort of finished, but not turned into an actual plugin that's publicly available).
