### ISSUE TITLE
were is your /path/to/mathquill.js

### ISSUE THREAD

**Issue by tomkidumbuyo** [mathquill/mathquill#618]
i cant seem to find the /path/to/mathquill.js to include in my website

**Comment by laughinghan** [comment]
That means the path that you downloaded MathQuill to. What are you trying to do with MathQuill?

**Comment by The-Penultimate-Defenestrator** [comment]
If you're trying to get a copy of `mathquill.js`, to include in your website, check [the Releases page](https://github.com/mathquill/mathquill/releases). There, you can download a zip file which includes `mathquill.js` and `mathquill.css`. Get it [here](https://github.com/mathquill/mathquill/releases/download/v0.10.1/mathquill-0.10.1.zip).

Then, you'll have to upload to your server `mathquill.min.js` and `mathquill.min.css` and include them in your project. There's no CDN hosted copy, to my knowledge.

**Comment by tomkidumbuyo** [comment]
so i created a ck editor plugin from your code... its not perfect but u
might like it...

On Sat, Apr 16, 2016 at 10:38 PM, Luke Deen Taylor <notifications@github.com

**Comment by The-Penultimate-Defenestrator** [comment]
So you've been successful in loading MathQuill now?

**Comment by tomkidumbuyo** [comment]
yeah i have... i used your first version. the one you stopped maintaining.
its a great library i cant thank you enough dude. also i created a version
that doesn't require a user to know tex at all. if you are interested i
could just give it to you.... it not that good but uyou could work on it....

On Sat, Apr 30, 2016 at 10:40 PM, Luke Deen Taylor <notifications@github.com

**Comment by The-Penultimate-Defenestrator** [comment]
Nice! I think that's been done before, see [Desmos](http://desmos.com), but if you want to share your code go ahead. I'm glad you got your issue resolved.
