### ISSUE TITLE
Mathquill not functionnal in android browsers

### ISSUE THREAD

**Issue by Narsil** [mathquill/mathquill#65]
Mathquill is not usable in (android at least) mobile browsers:

Tested on mathquill.github.com.

Phone: Android Nexus S (4.0)

Browser: Default one
Can type stuff, but cannot backspace, rendering is ok.

Browser: Chrome
Cannot  type anything which is problematic.

This is probably linked to all the keyboard event stuff going on with mathquill.

**Comment by nscozzaro** [comment]
I have a Pixel 2 phone with Chrome and the Mathquill demo on Mathquill.com doesn't work for me. I can click on the box and the browser automatically zooms to the box, but then when I type, the box doesn't respond at all. Suggestions?

**Comment by ajhyndman** [comment]
@nscozzaro, @otizzz Are you able to reproduce this bug with the latest version of MathQuill off of master?

I did some research yesterday, and I believe this issue was fixed in: https://github.com/mathquill/mathquill/pull/694

**Comment by nscozzaro** [comment]
@ajhyndman is there a link to a site using the latest version that I can try?

**Comment by bmintz** [comment]
@nscozzaro how about http://mathquill.com

**Comment by nscozzaro** [comment]
@bmintz as I said above, I tried it on Mathquill.com. 
I made a video of the issue: https://youtu.be/HanO60UzZF8
You'll notice that delete works, but nothing else. At the very end it unexpectedly started to work after accidentally pressing the return key (the blue arrow). But then I refresh the page and it doesn't work against

**Comment by ajhyndman** [comment]
Yeah, I'm not sure why but http://mathquill.com doesn't see to be running the latest version.

This should have the latest code:

http://many-worlds.glitch.me/mathquill/mathquill/branch/master/test/demo.html

**Comment by nscozzaro** [comment]
Yes that's working for me, thanks! (besides the fact that the square root looks rather wonky). 
I'll update to the latest version of Mathquill and hopefully that solves my issue.

**Comment by ajhyndman** [comment]
Awesome!

I'm going to close this issue.  If anyone runs into it again, please feel free to re-open or create a new issue.

**Comment by mgaouar** [comment]
Hi,

I am using Mathquill latest 0.10.1 and I have the same issue on Android devices, I can reproduce on mathquill.com as well, using the latest Android 8 device.

Any update on this?

Thanks,

**Comment by ajhyndman** [comment]
@mgaouar Are you able to provide some sample code that reproduces this issue?

mathquill.com is actually not running the latest MathQuill code, and is known to not work with Android.  I've tested the latest version, however, and have seen Android keyboards work.

It'd be great if we could update that, @laughinghan?

**Comment by mgaouar** [comment]
Hi I was using this visual editor https://www.jqueryscript.net/text/Simple-WYSIWYG-Math-Editor-With-jQuery-Mathquill-matheditor-js.html which has the latest released version of MathQuill, I updated my code with the code of the PR that fixes the issue and it's now working, is there any plan on releasing an official version of MathQuill that will have the fix? I just patched it by hand on site.

Thanks,

**Comment by mgaouar** [comment]
@ajhyndman thanks for the prompt reply by the way!

**Comment by ajhyndman** [comment]
Sorry, I'm not sure the answer to that one.  Maybe if you open a separate issue to ask about that, we can get a comment from one of the core maintainers.

**Comment by Giampa** [comment]
@mgaouar did you manage to solve the problem? I'm experiencing the same on Nexus 5x Oreo...

**Comment by IanNS333** [comment]
I am experiencing this same issue with google chrome for android, version 69.0.3497.100, my device is Samsing Galaxy S9 Plus.

I went directly to mathquill.com, and tried using the demo box for math input, but unfortunately it does not work.

**Comment by variablemayank** [comment]
@laughinghan Can I use this link in my own project ?.

**Comment by diophant-math** [comment]
Hello. It still doesn't work. And on the site you can only download version 0.10.1. I take it this is not the latest version? What needs to be changed in the code to fix this bug?
