### ISSUE TITLE
`Edit` handler is not called when typing a mismatched bracket

### ISSUE THREAD

**Issue by ajhyndman** [mathquill/mathquill#655]
**To reproduce:**

* open up http://mathquill.com/
* type: (3,4] into the field labelled *Type math here:*.
* Latex below the field looks like:
![image](https://cloud.githubusercontent.com/assets/11449340/16329981/770ded4c-3a29-11e6-94db-c026df9e365e.png)

MathQuill's internal state has been updated correctly at this point (to render `\left(3,4\right]`), but the edit handler wasn't called.

**Comment by ajhyndman** [comment]
I've submitted a pull request to fix this here:

https://github.com/mathquill/mathquill/pull/656

**Comment by laughinghan** [comment]
Nice catch!
