### ISSUE TITLE
\MathQuillMathField -- options cannot be configured

### ISSUE THREAD

**Issue by dominique-unruh** [mathquill/mathquill#664]
When creating an editable math field inside a static math field, it is not possible to specify options (the inner math field is initialized with `Options()`).

In particular, this means that one cannot have `edit` or `enter` handlers on the inner math fields.

I see several possible solutions:
* Use the same options for outer and inner math fields
* Specify in the options a key `innerOptions` or similar giving the options for all inner mathfields
* Specify in the options a key `innerOptions` or similar which gives a different option object for each inner math field (indexed by the name `name` of the inner math field `\MathQuillMathField[name]`)
* Allow to change the options after a math field has been initialized (then one could, e.g., use `mathfield.innerFields.name.addOptions(handlers:{...})`)

**Comment by dominique-unruh** [comment]
I just found out that the fourth solution is already implemented.
You can write:
```
mathfield.innerFields.name.addOptions(handlers:{...})
```

**Comment by laughinghan** [comment]
I assume the second comment is a typo, you mean `mathfield.innerFields.name.config({handlers: {...}})`?

Would #510 address your issue, if we fix the merge conflict?

**Comment by dominique-unruh** [comment]
Yes, it was a typo, I meant `config`.

----

I don't understand what #510 does.

I checked out the pull request, and replaced in `test/demo.html`
```$('.mathquill-static-math').each(function() { MathQuill.StaticMath(this); });```
by
```$('.mathquill-static-math').each(function() { MathQuill.StaticMath(this,{handlers:{edit:{function(m){console.log("inner field edited",m.latex())}}}})});```

From the description of #510, I would have expected that now the inner math fields near the bottom of the page have an edit handler, and that the console has messages `inner field edited`. This is not the case (in my test, with Chromium).
