### ISSUE TITLE
Text field not trigering edit event

### ISSUE THREAD

**Issue by SiebeVE** [mathquill/mathquill#705]
When you use the latex to insert text: `\text` And then type into the created field, the `edit` handler is not called.
This means, you can't live preview the text with the `edit` handler.
*Note: The backspace, triggers the `edit` handler when in the textfield.*

**Quick Fix**
Set a listener to the textarea to listen to a `keyup` event. This will trigger even when in a textfield of latex.

```javascript
var MQ = MathQuill.getInterface(2);
var mathField = MQ.MathField(document.getElementById('solution'), {
  handlers: {
    edit: function () {
      render_live_math();
    }
  }
});

var render_live_math = function(){
  // Live render the latex
  var liveLatex = mathField.latex();
  MQ.StaticMath(liveRender).latex(liveLatex);
};

$("#solution").on("keyup", "textarea", function(){
  render_live_math();
});
```

Quick Fix idea credits: @laughinghan

**Comment by drdrew42** [comment]
I recently ran into this issue myself and though I'd share my fix. 
I resolved the failure of text-mode to call the edit handler by updating the `.write` method for the TextBlock class as follows:

```javascript
var TextBlock = 
  ...
  _.write = 
    ...
    if (ch !== '$') {
      this.postOrder('reflow'); /* added */
      if (!cursor[L]) TextPiece(ch).createLeftOf(cursor);
      else cursor[L].appendText(ch);
      this.bubble('reflow'); /* added */
    }
```
(as defined in src/commands/text.js)
