### ISSUE TITLE
How to add caret symbol?

### ISSUE THREAD

**Issue by abhikhatri** [mathquill/mathquill#733]
I want to add caret symbol to mathquill but eventually it always add changes to power mode. Is there any way I can append '^' in the input area?

**Comment by jwmerrill** [comment]
You might be looking for \wedge. In what context do you want to add the
caret symbol?

**Comment by abhikhatri** [comment]
@jwmerrill I tried \wedge but it was not looking so great so I ended up embedding caret instead of the wedge icon in the mathquill source. But your answer really gave me the idea to do it this way. 👍 
Thanks man 👏👏👏👏👏👏
