### ISSUE TITLE
Pasting text into \text{} outputs mathquill source code in latex view

### ISSUE THREAD

**Issue by eeroan** [mathquill/mathquill#745]
How to reproduce:

Go to http://mathquill.com/
1) type in second box `\text` and press `Tab`
![image](https://cloud.githubusercontent.com/assets/114198/25306496/b2f145a6-2796-11e7-93b3-a6ce5cf26d76.png)
2) paste a letter or text
![image](https://cloud.githubusercontent.com/assets/114198/25306503/c634d128-2796-11e7-9939-7329efd19110.png)
3) Result: Latex view prints implementation code of `Variable`'s `_.text` -function
![image](https://cloud.githubusercontent.com/assets/114198/25306506/d8076e10-2796-11e7-883b-5ef2fa6cb167.png)

**Comment by limeb** [comment]
Yes please I would love a fix for this.
