### ISSUE TITLE
Superscript of tall expression

### ISSUE THREAD

**Issue by savthegood** [mathquill/mathquill#763]
Superscript of very tall expression is rendered kind of wrong, e.g. `(-5^(1/2))^2+3` (here 2 is superscript):
![image](https://user-images.githubusercontent.com/30241513/28280840-c1fe6e4a-6b2d-11e7-828c-6fe14542d249.png)

Probable way out is to add _reflow() method for LatexCmds.superscript as:

`
  _.reflow = function() {

     var $block = this.ends[R].jQ;//mq-sup

     $block = $block.parent() ;//mq-supsub

     var h = $block.prev().innerHeight() ;

     h *= 0.6 ;

     $block.css( 'vertical-align',  h + 'px' ) ;
  } ;
`

**Comment by kschaefe** [comment]
Do you have an image with the reflow in place?

**Comment by savthegood** [comment]
smth like this: 

![image](https://user-images.githubusercontent.com/30241513/28281326-5fe68ee8-6b2f-11e7-85b0-d24726a1347b.png)

**Comment by kschaefe** [comment]
That looks great.  Can you create a pull request for this?

**Comment by savthegood** [comment]
What the difference between ticket and pull request? I'm not used to github, sorry if a question is lame. Basically you ask to copy-paste this ticket in Pull Requests?

**Comment by kschaefe** [comment]
A pull request is your fork on github with the change that asks us to put it in place.  See
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
and
https://yangsu.github.io/pull-request-tutorial/

It's good for the project to get these changes via pull requests, so we can get sign-off on the Contributor License Agreement.

**Comment by savthegood** [comment]
oh well..whatever the reason is, but it didnt pass your tests. I'm not sure why. see pull request #764 .
