### ISSUE TITLE
How to prevent default keyboard appear from touch (React native using WebView)

### ISSUE THREAD

**Issue by pansitwattana** [mathquill/mathquill#770]

**Comment by kschaefe** [comment]
http://docs.mathquill.com/en/latest/Config/#substitutetextarea

**Comment by pansitwattana** [comment]
do you have an example for that?

**Comment by kschaefe** [comment]
This is what we use in our product:

    MathQuill.config({
        substituteTextarea: function() {
            var textArea = $('<span class="editor" role="textbox"></span>');
            textArea[0].select = angular.noop;
    
            textArea[0].val = function(val) {
                return textArea.data('__val', val);
            };
    
            textArea.on('keydown', function(event) {
                //we need to ensure that we have focus when MathQuill processes the key events
                if (document.activeElement !== textArea[0]) {
                    textArea[0].focus();
                }
            });
    
            textArea.on('keypress', function(event) {
                var value = String.fromCharCode(event.which);
    
                if (value === '$') {
                    event.preventDefault();
                } else {
                    textArea.val(value);
    
                    if (event.which === keyCodes.slash || event.which === keyCodes.right_arrow) {
                        event.preventDefault();
                    }
                }
            });
    
            return textArea[0];
        }
    });

The keydown and keypress may not be necessary for you, but solve a couple of problems for us.

**Comment by pansitwattana** [comment]
Thanks for the reply. I figured it out by replace textarea to span

```
mathField = MQ.MathField(mathFieldSpan, {
   substituteTextarea: () => document.createElement('span'),
});
```

**Comment by kschaefe** [comment]
Going to close this based on your last comment.

**Comment by kschaefe** [comment]
Discovered something recently.  You'll want to change your `keypress` handler a bit.  That approach will not cause the MQ `enter` handler to fire.  Consider this instead:

```
el.addEventListener('keypress', (event: KeyboardEvent) => {
  if (event.code === "Enter") {
    textArea.value = '\n';
  } else {
    textArea.value = event.key;
  }
});
```

**Comment by stevenschemers** [comment]
> Discovered something recently. You'll want to change your `keypress` handler a bit. That approach will not cause the MQ `enter` handler to fire. Consider this instead:
> 
> ```
> el.addEventListener('keypress', (event: KeyboardEvent) => {
>   if (event.code === "Enter") {
>     textArea.value = '\n';
>   } else {
>     textArea.value = event.key;
>   }
> });
> ```

Had this same realization later in the day after posting my comment as well. Thanks for putting this in here for others.
