### ISSUE TITLE
Braces don't render when element is temporarily hidden

### ISSUE THREAD

**Issue by CoryGH** [mathquill/mathquill#771]
I'm using mathquill within bootstrap tabs and it works works great when the tab containing the mathquill-driven equation is the default one, but when it is not the parenthesis don't appear until you begin editing within an parenthesis or create a new parenthesis anywhere in the mathquill control.

**Comment by kschaefe** [comment]
MathQuill does not render properly with `display: none`.  You can manually call `reflow` on each MQ expression in the tab when it is made visible or use `visibility: hidden` instead.

**Comment by CoryGH** [comment]
@kschaefe Thanks.
