### ISSUE TITLE
Mathquill angular support

### ISSUE THREAD

**Issue by shashank-sharma** [mathquill/mathquill#778]
Hi, I am trying to figure out that is it possible to import Mathquill in Angular 4 project and then use it inside typescript file ?

So far I tried to import mathquill but failed to do so.

**Comment by kschaefe** [comment]
@shashank-sharma Did you figure out the answer to your problem?  If so, would you mind putting it in this issue for posterity?

**Comment by shashank-sharma** [comment]
Ok so I was trying to implement mathquill feature inside typescript and I was confused as if how I can import mathquill. So I did:

`declare var MathQuill: any;`

And then use it as usual. For example if you want to run this as a function when any key is pressed then :
```
    insertMathQuill(){
        var MQ = MathQuill.getInterface(2);
        var answerSpan = document.getElementById('mqq');
        var answerMathField = MQ.MathField(answerSpan, {
     ... ...
        });
```
    }
