### ISSUE TITLE
Pressing Backspace within a `\MathQuillMathField` block deletes text from the parent

### ISSUE THREAD

**Issue by ajhyndman** [mathquill/mathquill#785]
![kapture 2017-11-23 at 11 09 35](https://user-images.githubusercontent.com/11449340/33154772-efddfe9a-d03e-11e7-89f1-fd76d6004641.gif)

What I expected to happen:

Only the character within the `\MathQuillMathField` was deleted (or nothing, if there were no text inside `\MathQuillMathField`).

I haven't looked into the code too far yet, to see what's happening, but it looks like we might just be handling bubbling events without vetting the target?

**Comment by kschaefe** [comment]
Yeah, that's a problem.  My company only uses them inside static MathQuill blocks, where this issue isn't a problem.

That being said, what's the use case for having editable fields inside editable fields?

**Comment by ajhyndman** [comment]
Hmm.  I actually still run into this in the static MathQuill case.  It manifests slightly differently:

![kapture 2017-11-30 at 18 47 33](https://user-images.githubusercontent.com/11449340/33419536-fe8a5464-d5fe-11e7-8f54-6b1c8df4024f.gif)
