### ISSUE TITLE
\text{} element alone in editor not serialized with .latex() unless other math symbols included

### ISSUE THREAD

**Issue by jaltekruse** [mathquill/mathquill#794]
![image](https://user-images.githubusercontent.com/365366/35550535-a3656af4-053f-11e8-9088-71d95fc8fbc0.png)

I haven't been able to confirm this is failing in the serialization process. This might also be an issue with not receiving an edited event when pressing enter to create the text sub-box. For example like in the GIf above: \asdf [enter] (I think it is fine to not get edited events while users may still be typing in a latex symbol).

This bug is making me less confident about exposing any of the latex symbols that require a backslash prefix to users in my app (without making them auto-symbols), as mistyping a symbol creates one of these text elements. Given the current structure of my app this can clear what user types in Mathquill fields. I am using a React wrapper from the Khan team that causes a re-render event based on the current app state on blur, so I need to have up-to-date latex for what is in the field when something loses focus. I'll file an issue over there as well to see if they have any ideas about possible workarounds.

**Comment by jaltekruse** [comment]
I guess github doesn't support gifs, here's a link: http://gph.is/2GvI62q

**Comment by surenk6** [comment]
I have encountered this issue as well. I am using this product in development. Please give a solution to this issue asap.

**Comment by narek-sv** [comment]
This is annoying, please fix it as fast as possible!!!

**Comment by vuvkar** [comment]
Yeah, me too. isn't there any temporary solution guys? :/

**Comment by VahanArsenyan** [comment]
Same problem :( so sad about it. Pls solve it guys :(

**Comment by ArevikDev** [comment]
Same here

**Comment by jaltekruse** [comment]
It can be very frustrating as a maintainer to have users that are certain that their problems are the most important for the project. If this is such a big problem for all of us we can put some of our own effort into trying to address it. I was just reporting the issue to see if I could get some help from others more familiar with the codebase. Please keep this in mind when you are commenting on issues and feature requests in the future.

Several of your responses are fine to report running into this problem as well, but insisting this needs to be resolved ASAP and accusing the maintainers of not prioritizing this correctly gets old fast.
