### ISSUE TITLE
Mathquill documentation is not available

### ISSUE THREAD

**Issue by lxhan** [mathquill/mathquill#801]
@laughinghan @jneen @stufflebear I don't know since when but website and docs are down. Can you please tell are you going to fix this and if not where can I get latest documentation? Thank you very much

**Comment by laughinghan** [comment]
mathquill.com works for me, but not docs.mathquill.com

That's weird! In the meantime, http://mathquill.readthedocs.io/en/latest/ is still up!

**Comment by laughinghan** [comment]
Huh, I must have had mathquill.com's DNS cached. Anyway, DNS has been restored, the MathQuill website should be fully functional again. Thanks for letting us know, sorry about that!
