### ISSUE TITLE
Potential License Violation

### ISSUE THREAD

**Issue by MohamedAlFahim** [mathquill/mathquill#816]
The publicly available (and well known) proprietary web application Symbolab uses Mathquill without disclosing its source code. After reading https://www.mozilla.org/en-US/MPL/2.0/FAQ/, I found Symbolab to be potentially violating the MPL 2.0 license. Here is a screenshot:
![mathquill potential license violation](https://user-images.githubusercontent.com/31521089/41805220-65908e34-765a-11e8-8619-4e9d354631b3.png)
You can clearly see usage of Mathquill. After checking out Symbolab, I still could not find any CLEAR disclosure of source. Otherwise, I might have misread or misinterpreted the terms.

**Comment by laughinghan** [comment]
Thanks for looking out for us! They've bought a commercial license though.
