### ISSUE TITLE
How can i update the span content that displays \MathQuillMathField LaTeX ?

### ISSUE THREAD

**Issue by AliOsamaHassan** [mathquill/mathquill#827]
In the following example, how can i update the span content `\sqrt{ \MathQuillMathField{x}^2 }` to be **_dynamically changeable_** and i can send my own span content, which will has already a **\MathQuillMathField{ }** that will be **_editable_**.

```
<span id="fill-in-the-blank">\sqrt{ \MathQuillMathField{x}^2 }</span>
<script>
  var fillInTheBlank = MQ.StaticMath(document.getElementById('fill-in-the-blank'));
  fillInTheBlank.innerFields[0].latex() // => 'x'
  fillInTheBlank.innerFields[1].latex() // => 'y'
</script>

```

**Comment by kschaefe** [comment]
I don't understand the question.  Can you please rephrase or perhaps include a picture.

**Comment by AliOsamaHassan** [comment]
See the attached pictures ..
I just want to display a math formula that has _**known (non editable)**_  and _**unknown (editable)**_ parts, so i've used **\MathQuillMathField** LaTeX command that can be embedded in  **MQ.StaticMath**
Now, i want to overwrite or change the content on this span
`<span id="fill-in-the-blank">\sqrt{ \MathQuillMathField{x}^2 }</span>
` 
![examples](https://user-images.githubusercontent.com/19392865/45695981-d6d0d700-bb62-11e8-90ab-a443d0b40b73.PNG)
![example](https://user-images.githubusercontent.com/19392865/45695982-d6d0d700-bb62-11e8-800f-d5ffefb9886d.PNG)

**Comment by kschaefe** [comment]
Use `latex` on the MQ for that span.  You can change all of the contents.

**Comment by AliOsamaHassan** [comment]
Can you give me an example, please ?
Thanks so much ! @kschaefe

**Comment by AliOsamaHassan** [comment]
That's what i want thanks so much !

**Comment by kschaefe** [comment]
Great.  Closing.
