### ISSUE TITLE
convert from text to latex 

### ISSUE THREAD

**Issue by moroclash** [mathquill/mathquill#828]
### how I can use mathquill to convert math equation like 
` 1/2 + 3/4 + 3*4`
### to be latex like 
`\frac{1}{2}+\frac{3}{4}+3\cdot 4`
#### I use mathquilefiled to write the equation as text and after rendering it I use this mathquilefiled to return latex of text that written but there is a bug in mathquilefiled.

I write `1/2 + 3/4 + 3*4` and it should return   `\frac{1}{2}+\frac{3}{4}+3\cdot 4`
but it return `#+\frac{3}{4+3\cdot4}`.

**Comment by kschaefe** [comment]
No.  There is a poorly supported `text` function, but because the different text formats are different, there's no one approach to take.  Expect `text` to be removed in the future.

Your best bet is to find/create a text-to-latex converter for the text format that you're using.
