### ISSUE TITLE
can't get correct text from MathField

### ISSUE THREAD

**Issue by sashaalesin** [mathquill/mathquill#840]
If i have a editable MathQuill and i will write in it " 1 / 2 " and then get content:
`mathField.latex() --> \frac{1}{2}`,
`mathField.text() --> (1)/(2)` (where did the brackets come from?)
But if i will write "2 ^ -3":
`mathField.latex() --> 2^{-3}`
`mathField.text() --> 2^-3` (why without brackets?)

As a result if i will write "2 ^ 1 / 2" in field i can't get valid text like "2 ^ (1 / 2)" or "2 ^ ((1) / (2))", i get "2 ^ (1) / (2)" and parse it how `2 ^ 1 / 2 = 1`. 

Maybe a can paste brackets automatically when user write " ^ "? And if you automatically write brackets in the fractions, why you can't write it in the powers? Thanks

**Comment by sashaalesin** [comment]
I know about `charsThatBreakOutOfSupSub`, but id don't protect from " 2 ^ 1/2 "

**Comment by jwmerrill** [comment]
MathQuill's `.text()` format doesn't really come with any guarantees. If you want to parse MathQuill's output, you're probably better off attempting to parse `.latex()` than `.text()`.
