### ISSUE TITLE
a < b is broken

### ISSUE THREAD

**Issue by mwz921804620** [mathquill/mathquill#883]
when I use MQ.StaticMath(a<b), I can not find velue.

**Comment by ChristopherHX** [comment]
I don't think it broken use `MQ.StaticMath('a<b')`, you forget the string literal `'a<b'` or `"a<b"`
JS will execute this as it is javascript code, `a<b` compares a and b before passing it to mathquill

**Comment by jaltekruse** [comment]
Not a bug with Mathquill, so I'm going to close this. Thanks for providing an answer to the question @ChristopherHX!
