### ISSUE TITLE
after mathField.write("\\left(\\right)"), i want to put cursor into "( )" automatically,how can i make it?

### ISSUE THREAD

**Issue by BubblyJuly** [mathquill/mathquill#884]

**Comment by CaptainIRS** [comment]
You can use `mathField.cmd('(');` to automatically place the cursor and take care of the size of parantheses as you enter values into it. In case you want to do it manually, you can use `mathField.write('Left');` after `mathField.write("\\left(\\right)");`

**Comment by BubblyJuly** [comment]
> You can use `mathField.cmd('(');` to automatically place the cursor and take care of the size of parantheses as you enter values into it. In case you want to do it manually, you can use `mathField.write('Left');` after `mathField.write("\\left(\\right)");`

thanks for you answer! but when i use 'mathField.cmd(‘(')' ,it also doesn't put cursor  into "( )" automatically.

**Comment by CaptainIRS** [comment]
It's possibly because focus is lost after you issue the command. You can use `mathField.focus();` after `mathField.cmd('(');` to manually focus the math field. Then, the cursor would be placed into ().
