### ISSUE TITLE
How to insert nth-root?

### ISSUE THREAD

**Issue by arguiot** [mathquill/mathquill#897]
I try to replicate what is done on Desmos when pressing this button:
<img width="77" alt="Capture d’écran 2020-05-29 à 11 34 22" src="https://user-images.githubusercontent.com/18022260/83277627-59b38d00-a1a0-11ea-88c3-b9327c1b07de.png">

Unfortunately, when I try to use `.write("\\sqrt[n]{}")` is just doesn't work. I can't look at Desmos source code because it's generated and forgot to add a source map...

I also didn't find any example in your tests.

**Comment by sashaalesin** [comment]
Hi, `.write("\\sqrt[n]{}")` works for me without problems.

**Comment by arguiot** [comment]
@sashaalesin I realized the problem was from my side, `\\` was evaluated `\`, that's why... thanks!
