### ISSUE TITLE
Sqrt shortcut

### ISSUE THREAD

**Issue by cajoek** [mathquill/mathquill#901]
I know this question has been asked before but that was 10 years ago..
Is it possible to add custom shortcuts in a simple way? Specifically a shortcut for \sqrt like Alt+v?

**Comment by bbmarkus** [comment]
If you have a UI button for doing the same thing (e.g. call math field's method in a buttons onclick or something, write or cmd should do the trick) then you may just be able to use the html accesskey attribute on that button :).
