### ISSUE TITLE
carret to pow()

### ISSUE THREAD

**Issue by gershis1** [mathquill/mathquill#912]
I was wondering if there is a way to transform the notation of latex by defect.

When I write:  (2)^(2)

I get: `\left(2\right)^{\left(2\right)}`

But I want something like `\POW \left(2\right),{\left(2\right)}` so it seems like POW(2),(2)

For this I use a button that inserts **)^(** to the editor.

Some idea?

**Comment by laughinghan** [comment]
I'm afraid MathQuill doesn't let you configure custom LaTeX dialects. It's focused on exporting LaTeX that is compatible with KaTeX and MathJax primarily, and secondarily pdflatex, which is the most common LaTeX renderer (used by MacTeX, etc)
