### ISSUE TITLE
\text{} inputs not tracked

### ISSUE THREAD

**Issue by timkinsman** [mathquill/mathquill#918]
When I type some text in a \text{} block it does not save till I either backspace within the text block or append a character after exiting the text block.

How do I track whats being typed in the text block so I can store it as I go and doesn't disappear when I move to another part of my application and return? Thanks

![Screenshot (26)](https://user-images.githubusercontent.com/40594657/97135419-1fc2d300-17a0-11eb-803d-b95d1fb78bc0.png)

![Screenshot (27)](https://user-images.githubusercontent.com/40594657/97135426-24878700-17a0-11eb-87ee-332216c1f6c7.png)

![Screenshot (30)](https://user-images.githubusercontent.com/40594657/97135427-26e9e100-17a0-11eb-9449-1088ecd8568e.png)

**Comment by jaltekruse** [comment]
The version of mathquill on the site is stale, but this issue has been fixed on the master branch.

https://github.com/mathquill/mathquill/issues/794
