### ISSUE TITLE
Convert formatted text to raw user input

### ISSUE THREAD

**Issue by Artexety** [mathquill/mathquill#922]
Is it possible to convert this:
1+\frac{2}{3}\cdot4

back to its original form: 
1+2/3 * 4

**Comment by drlippman** [comment]
You said "original form", but Mathquill's input form is TeX, not that form.  Maybe you meant the keystrokes used, but what would you expect to get if the user used arrow keys or mouse clicks to move around or edit the expression? 

I'm guessing what you're really wanting is a way to convert the TeX output to a calculator-style notation which you can then evaluate for some purpose.

I have a script I use for this purpose, which is the `MQtoAM` function at the bottom of [this script](https://github.com/drlippman/IMathAS/blob/master/mathquill/AMtoMQ.js).  But be aware it is very limited in what TeX it can convert to asciimath; it only really supports calculator operations like fractions, roots, basic functions, etc.  And it doesn't make implicit multiplication explicit, so you'd have to handle that in your evaluation routine.
