### ISSUE TITLE
MacOS build failed:sed: 1: "build/mathquill-basic.js": undefined label 'uild/mathquill-basic.js'

### ISSUE THREAD

**Issue by rawbin-** [mathquill/mathquill#925]
using master and run npm install on MacOS 11.2.2

# make basic 

cat src/intro.js node_modules/pjs/src/p.js src/tree.js src/cursor.js src/controller.js src/publicapi.js src/services/parser.util.js src/services/saneKeyboardEvents.util.js src/services/exportText.js src/services/focusBlur.js src/services/keystroke.js src/services/latex.js src/services/mouse.js src/services/scrollHoriz.js src/services/textarea.js src/commands/math.js src/commands/math/basicSymbols.js src/commands/math/commands.js src/outro.js build/.exists--used_by_Makefile | ./script/escape-non-ascii > build/mathquill-basic.js
sed -i     s/{VERSION}/v0.10.1/ build/mathquill-basic.js
sed: 1: "build/mathquill-basic.js": undefined label 'uild/mathquill-basic.js'
make: *** [build/mathquill-basic.js] Error 1

**Comment by jaltekruse** [comment]
It looks like this might be part of the issue the 'b' looks to have been chopped off of the from of this path -  undefined label 'uild/mathquill-basic.js'.

Are you sure you have a clean checkout of master? Could you post your npm version?

**Comment by rawbin-** [comment]
![image](https://user-images.githubusercontent.com/8169783/115646295-77f41f80-a354-11eb-8dba-e91bf4dae98b.png)

this line makes it to work

**Comment by jwmerrill** [comment]
I just upgraded from macOS Catalina to Big Sur, and I'm running into this now too.

I see that the `sed` that macOS is shipping now supports the `-r` option (excerpt from `man sed`):
```
-r      Same as -E for compatibility with GNU sed.
```

So this logic is now detecting macOS's sed as "GNU", even though it still needs the "BSD" behavior for `-i`.

**Comment by jwmerrill** [comment]
A bit of googling is telling me that using `perl` for this purpose is more portable than using `sed`.

I tried doing
```
SED_IN_PLACE = perl -pi -e
```

and this gets the build working for me again, although I think it will be better to just inline this to avoid confusingly calling it SED now that it's perl.

I can put up a PR for this.
