### ISSUE TITLE
Variables  with more than one letter

### ISSUE THREAD

**Issue by Corcharelli** [mathquill/mathquill#927]
Hi,

I need to use variables with more than one letter in my formulas. The problem is than the text() function doesn't return the typed text.
For example, if I type **`varx * 2 - vary`**, the text() function returns **`v*a*r*x*2 - v*a*r*y`**
How can I do that??

Thanks!

**Comment by kschaefe** [comment]
`text()` should never be relied upon.  It's mostly there for testing purposes and is not intended to represent in any way what was _actually_ typed.

That being said, if you know the variables up front, you could use `autoCommands` config option, cf. http://docs.mathquill.com/en/latest/Config/#autocommands
