### ISSUE TITLE
Dynamically Creating and Removing Editable Fields

### ISSUE THREAD

**Issue by Ephraim-Bryski** [mathquill/mathquill#928]
I'm planning on using MathQuill for a site to perform symbolic math, and I want to control the display, specifically creating and removing editable fields, based on what a user types and where the cursor is located. 

For example, if the user types solve into an editable field (created using \MathQuillMathField), it should be replaced with:
\text{solve} [Editable Region] \text{for} [Editable Region]

As another example, I want the user to be able to fill in a matrix of values, each value being an editable field. I would like the matrix to always have one more number of rows than filled rows and one more number of columns than filled columns, so the user can keep on expanding the matrix. Then when the user clicks out of the matrix, it would check if a grid of values are filled, and if they are, it would replace the editable regions with static math and remove the extra row and column.

How difficult would procedures like these be in MathQuill. Is MathQuill recommended for this type of application?

Thanks.

**Comment by kschaefe** [comment]
You could use an `edit` or `enter` handler.  The latter would force your users to press `enter` for you to determine changes.  Then, in the handler, you'd need to evaluate the state of the `innerFields` to determine if you need to add a row, etc.

Yes, this is doable in MQ, but you'll need to be writing some custom handler code to make it work.

**Comment by Ephraim-Bryski** [comment]
Thank you! This works perfectly well. However, I realize that MathQuill doesn't support cases (or other LaTex using \begin), which is crucial for what I want to make (it's built around creating systems of equations). I've noticed [pull requests](https://github.com/mathquill/mathquill/pull/661) about it which haven't yet been merged. Is there anything I could use now, or any plans to add cases? If not, are there any other JavaScript equation editors which can achieve this? (MathLive can, but it also doesn't seem able to create editable fields).

(It also doesn't support \hfill it seems, which is something else I was planning on using).
