### ISSUE TITLE
v0.9.x → v0.10.0 Migration Guide Missing Instruction

### ISSUE THREAD

**Issue by reptile18** [mathquill/mathquill#931]
Hello, trying to migrate a v0.9x implementation that I was handed. and [this guide](https://github.com/mathquill/mathquill/wiki/v0.9.x-%E2%86%92-v0.10.0-Migration-Guide) definitely is helping, but now I'm stuck on this line in our code ```$('.mathquill-embedded-latex').mathquill('mathquill-embedded-latex');``` I think there should be instructions in that guide on how to migrate this line.

**Comment by drlippman** [comment]
That appears to be covered in the guide you linked to, in the section titled "Note about .mathquill-editable etc"

**Comment by reptile18** [comment]
Ah, I saw that part of the article, but thought it was automated and didn't realize that this code snippet is doing the same thing.
