### ISSUE TITLE
\dot is broken

### ISSUE THREAD

**Issue by jaltekruse** [mathquill/mathquill#945]
@karoltarasiuk  excuse me, how can I show recurring decimal dot in MathQuill.
It seems can not match the right latex string,thanks.
![image](https://user-images.githubusercontent.com/6788979/54006513-927cd600-4198-11e9-9738-5420ad03b0bf.png)

_Originally posted by @xutaogit in https://github.com/mathquill/mathquill/issues/561#issuecomment-470795649_

**Comment by jwmerrill** [comment]
We think the problem here might just be that mathquill.com is running on a pretty old release of mathquill

**Comment by kevinbarabash** [comment]
I wasn't able to repro this on Safari or Chrome.
<img width="659" alt="Screen Shot 2021-11-20 at 5 07 41 PM" src="https://user-images.githubusercontent.com/1044413/142742236-337d0f47-c970-493a-8412-8187ad95e368.png">

**Comment by jaltekruse** [comment]
@kevinbarabash Thanks for testing this out, this was referring to \dot for producing a dot over a given symbol or set of symbols. @jwmerrill actually raised a concern about what surface area of LateX and different packages we want to consider for Mathquill when seeing this as apparently it isn't very standard.

This feature is working fine for me on master, I forgot when I created this after seeing the earlier comment that the Mathquill website is pretty far out of date, which is where I had tested before creating this issue. I have it on my list of things to do to get the site updated.

**Comment by jwmerrill** [comment]
>  @jwmerrill actually raised a concern about what surface area of LateX and different packages we want to consider for Mathquill when seeing this as apparently it isn't very standard.

Heads up, I was wrong about `\dot` not being in a common package. I just forgot that it has a required argument, so `\dot` is an error, but `\dot{x}` draws x with an overdot, like this:
<img width="563" alt="Screen Shot 2021-11-22 at 2 35 54 PM" src="https://user-images.githubusercontent.com/48409/142924075-8402d527-add9-4822-ba82-fe0d9a616952.png">
