### ISSUE TITLE
Superscript vertical height may not be adjusted after deleting characters

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#950]
Repro:

1. In mathquill master (note, not mathquill.com currently because that is behind master at the moment), paste in `\left(x^{\frac{1}{\frac{2}{3}}}\right)^2`
    <img width="58" alt="Screen Shot 2021-11-22 at 3 15 09 PM" src="https://user-images.githubusercontent.com/48409/142928872-74702ee7-5136-4546-8c1e-ba8210cb322d.png">
2. Place your cursor after the `3` innermost denominator
    <img width="57" alt="Screen Shot 2021-11-22 at 3 16 09 PM" src="https://user-images.githubusercontent.com/48409/142929003-f28ebc56-11a1-4971-a10f-6a1286fb9b23.png">
3. Press backspace four times to delete both denominators
    <img width="51" alt="Screen Shot 2021-11-22 at 3 16 38 PM" src="https://user-images.githubusercontent.com/48409/142929070-81d3939c-43e6-4541-a17c-30a3ca2c5d12.png">
    
This leaves a superscript stranded far above the parens it applies to.

Note, you don't actually need a nested fraction--that just makes the issue easier to see.

Relevant issues:
* https://github.com/mathquill/mathquill/issues/763
* https://github.com/mathquill/mathquill/pull/764
* https://github.com/mathquill/mathquill/pull/779

I think this comment may be saying this is a known caveat of the current implementation: https://github.com/mathquill/mathquill/pull/779#issuecomment-332029992

**Comment by laughinghan** [comment]
Yeah #764 and #779 don't really work, the SupSub doesn't get reflow-ed when its sibling changes in height
