### ISSUE TITLE
Customize text conversion of input

### ISSUE THREAD

**Issue by Ephraim-Bryski** [mathquill/mathquill#998]
Certain keywords (e.g. "sin") are automatically converted into unitalicized text format when typed in as input.

I was wondering if these keywords could be customized for a certain input field? 

- Is it possible to remove certain keywords (such as "Pr")?
- Is it possible to add keywords which would have the same behavior (for my case, I want "solve" to be a keyword)?
- Ideally this could be dynamic, as in I could specify the keywords for a particular field in a function call?

Thank you!

**Comment by drlippman** [comment]
It sounds like you're looking for the `autoCommands` and/or `autoOperatorNames` [config options](https://docs.mathquill.com/en/latest/Config/).  You can indeed customize the configuration for each element.

**Comment by Ephraim-Bryski** [comment]
Thank you! Adding the keywords to `autoOperatorNames` works.
